apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - sources
  - gateway-api
  - cilium
  - nvidia-device-plugin
  - local-path
  - cert-manager
  - configs
